AllCops:
  DisplayCopNames: true
  
Rails:
  Enabled: false

Style/Encoding:
  Enabled: false
  
Style/StringLiterals:
  Enabled: false
  
Style/DoubleNegation:
  Enabled: false
  
Style/GlobalVars:
  Enabled: false
  
Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false
  Max: 90
  
Metrics/MethodLength:
  Enabled: false
  
Metrics/ClassLength:
  Enabled: false
  
Metrics/CyclomaticComplexity:
  Enabled: false
  
Metrics/PerceivedComplexity:
  Enabled: false
  
Metrics/AbcSize:
  Enabled: false